Repository GEOS-ESM/GEOS_Util, pull requests merged in 2024-02, with the labels that each got.

#53 no remap when not necessary
  CHANGELOG.md
  pre/remap_restart/remap_base.py
  pre/remap_restart/remap_catchANDcn.py
  pre/remap_restart/remap_lake_landice_saltwater.py
  pre/remap_restart/remap_restarts.py
  pre/remap_restart/remap_upper.py
Labels: 0 diff trivial, non-0-diff for remap_restarts.py

#56 Move to use cp and tar at NAS
  CHANGELOG.md
  post/gcmpost.script
Labels: 0 diff

#58 prepare for sparse checkout
  CHANGELOG.md
  CMakeLists.txt
  pre/CMakeLists.txt
Labels: 0 diff

#60 [skip ci] Uptick to v2.0.6
  CHANGELOG.md
Labels: 0 diff trivial

#57 Transport updates and montage fixes 2024-02-08
  CHANGELOG.md
  plots/grads_util/corcmp.gs
  plots/grads_util/corcmp_plot.gs
  plots/grads_util/corcmpz_plot.gs
  plots/grads_util/getdates.gs
  plots/grads_util/makezdif2.gs
  plots/grads_util/makezdif3.gs
  plots/grads_util/pause.gs
  plots/grads_util/rmscmp_plot.gs
  plots/grads_util/rmscmpz_plot.gs
  plots/grads_util/seasonal
  plots/grads_util/seasonalf
  plots/grads_util/setdates.gs
  plots/grads_util/zonal.gs
  plots/gwd/gwd
  plots/hcmp/hcmp2
  plots/landscape.script
  plots/lcmp/VERIFICATION.MERRA2.rc
  plots/portrait.script
  plots/res/VERIFICATION.merra.rc
  plots/res/epflx.gs
  plots/res/epflx_diff.gs
  plots/res/plot_season.gs
  plots/res/res
  plots/res/res_3.gs
  plots/res/setup_epflx.gs
  plots/res/setup_wstar.gs
  plots/res/turn_around_lats.gs
  plots/res/zonal.gs
  plots/zcmp/progz
  plots/zcmp/zcloseplt
  post/flat2hdf.F
  post/gcmclim.script
  post/gcmpost.script
  post/stats.F90
Labels: 0 diff
