Repository GEOS-ESM/GEOS_Util, pull requests merged in 2025-04, with the labels that each got.

#132 resolved issue #131 in GEOSgcm v12
  pre/remap_restart/remap_questions.py
  pre/remap_restart/remap_utils.py
Labels: 0 diff trivial

#125 Remapping seaicethermo_import_rst
  CHANGELOG.md
  pre/remap_restart/remap_lake_landice_saltwater.py
Labels: 0 diff

#127 Remove NCCS OS detection
  CHANGELOG.md
  pre/remap_restart/remap_catchANDcn.py
  pre/remap_restart/remap_upper.py
  pre/remap_restart/remap_utils.py
Labels: 0 diff

#128 Fix issue with movestat and multi-month seasons
  CHANGELOG.md
  plots/movestat
Labels: 0 diff, bugfix

#135 [skip ci] Prepare CHANGELOG.md for v2.1.7
  CHANGELOG.md
Labels: 0 diff trivial
